package com.example.customermobileapplication.ui.navigation

object Routes {

    const val HOME_SCREEN = "HOME"
    const val SPLASH_SCREEN = "SPLASH_SCREEN"
    const val START_SCREEN = "START_SCREEN"
    const val LOGIN_SCREEN = "LOGIN_SCREEN"
    const val OTP_SCREEN = "OTP_SCREEN"
    const val SIGNUP_SCREEN = "SIGNUP_SCREEN"
    const val PROFILE_SCREEN = "PROFILE_SCREEN"
    const val BOOKING_SCREEN = "BOOKING_SCREEN"
    const val SERVICE_SCREEN = "SERVICE_SCREEN"
    const val PRODUCTS_SCREEN = "PRODUCTS_SCREEN"
    const val TREATMENT_PLAN_SCREEN = "TREATMENT_PLAN_SCREEN"
    const val ABOUT_SCREEN = "ABOUT_SCREEN"
    const val CONTACT_SCREEN = "CONTACT_SCREEN"
    const val REFER_SCREEN = "REFER_SCREEN"
    const val UPDATE_SCREEN = "UPDATE_SCREEN"
    const val ORDER_SCREEN = "ORDER_SCREEN"
    const val LASER_HAIR_PACKAGE_SCREEN = "LASER_HAIR_PACKAGE_SCREEN"
    const val MEDI_FACIAL_PACKAGE_SCREEN = "MEDI_FACIAL_PACKAGE_SCREEN"
    const val LASER_HAIR_WOMEN = "LASER_HAIR_WOMEN"
    const val LASER_HAIR_MEN = "LASER_HAIR_MEN"
    const val OXYHYDRA_FACIAL = "OXYHYDRA_FACIAL"
    const val OXYGENEO = "OXYGENEO"
    const val RF_SKIN_TIGHT = "RF_SKIN_TIGHT"
    const val DERMAFRAC = "DERMAFRAC"
    const val PRODUCT_DETAIL_SERUM = "PRODUCT_DETAIL_SERUM"
    const val PRODUCT_DETAIL_WASH = "PRODUCT_DETAIL_WASH"
    const val PRODUCT_DETAIL_MOISTURIZER = "product_detail_moisturizer"
    const val PRODUCT_DETAIL_PIGMENTATION = "product_detail_pigmentation"
    const val PRODUCT_DETAIL_ANTIOXIDANT = "product_detail_antioxidant"
    const val PRODUCT_DETAIL_SUNSCREEN = "product_detail_sunscreen"
}